5주차 미션 제출 (김다애)
daaeaad/frontend-mission pull request #6
Opened 2022-02-13 03:46 UTC by daaeaad

# 5주차 미션 제출 (김다애)

## 접근 방법

### 기능 구현 요구사항
- [x] 장바구니 목록 페이지 만들기
  - [x] 사용자의 장바구니 목록 보여주기
  - [x] 주문하기 버튼을 클릭하면 결제 화면으로 이동
- [x] 결제하기 페이지 만들기
  - [x] 결제에 필요한 사용자 정보 입력란 만들기
  - [x] 장바구니 페이지에 있었던 상품 목록 보여주기
  - [x] 총 결제 예상 금액 보여주기

### 추가한 요구사항
- [x] 장바구니 목록
  - [x] 상품 수량 표시, 증가 혹은 감소 버튼 추가
  - [x] 목록 삭제하기
  - [x] 목록 선택하기
  - [x] 선택된 목록만 총 수량과 총 가격 계산에 포함
  - [x] 개별 목록 바로구매하기 버튼과 기능 추가

## 특이사항

* [x] 고생해주신 다른 수강생분들과 강사님 감사합니다! 개인적으로 완성도 면에서 아쉬운게 많았지만 그래도 많이 배울 수 있는 기회여서 보람 찼습니다. :)

## 제출 후 확인

* [ ] 본인의 구현 결과를 `dev` 브랜치에 구현하고, `dev` 브랜치에서 `submission` 브랜치로 PR을 보내주세요.

CC: @externship-master  @lkaybob

2022-02-14 05:54 UTC, k12ms26 requested changes
[좋은 점/잘한 점]
수량이랑 세일 하는 가격까지 렌더링 하셔서 진짜 쇼핑몰처럼 꾸미신 것이 아주 인상깊습니다 👍 👍 

[의견제시]
코멘트 달아두었습니다 :) 그동안 너무 고생많으셨어요 😄

2022-02-14 05:54 UTC, k12ms26 commented on mission/src/components/Footer.vue
> +        <div data-test="" class="flex row align_center lay_1">
선언하지 않은 속성은 제거하셔도 될것 같습니다! 😮

2022-02-14 05:54 UTC, k12ms26 commented on mission/src/router/index.js
> +    beforeEnter: (to, from) => {
이 메서드의 용도가 어떤건지 여쭤봐도 될까요?

2022-02-14 16:24 UTC, Subinhyun reviewed
다애님이 구현하신 것을 보면서 진짜 쇼핑몰인줄 알았습니다...
추가적으로 구현하신 부분도 많아서 참고할 부분이 많네요 !
그리고 Composition API를 사용한 부분도 인상깊습니다!! 👍🏻
배울 점이 너무 많아서 저도 나중에 참고하여 추가로 구현해보겠습니다 ㅠㅠ
고생하셨습니다!!

2022-02-14 16:24 UTC, Subinhyun commented on mission/src/router/index.js
> +    beforeEnter: (to, from) => {
저도 궁금합니다!

2022-02-14 17:18 UTC, daaeaad commented on mission/src/router/index.js
> +    beforeEnter: (to, from) => {
앗 이건 아직 구현하지 않은 기능이긴 한데..
결제 페이지에서 이전 페이지가 상품 상세 페이지 였는지 장바구니 페이지 였는지 구분하기 위한 용도에요!

저는 실제 서비스 중인 쇼핑몰 앱을 많이 참고했는데
A라는 상품이 장바구니에 있을 때 장바구니 페이지에서 구매하기 까지 완료하면 해당 상품이 장바구니에서 삭제되고,
A 상품을 장바구니 페이지가 아니라 상품 상세 페이지에서 구매하기 까지 완료하면 장바구니 목록에서 A상품을 삭제하지 않고 유지 하더라구요 😶

그래서 어떤 상품에 대한 주문 및 결제를 완료하고 장바구니 목록에서 해당 상품을 삭제하는 함수를 실행할 때, 
이전 페이지가 장바구니 페이지 였는지 상품 상세 페이지 였는지를 조건으로 사용하기 위해서 추가해두었습니다!
이전 페이지를 알기 위해서 결제 페이지로 이동 되기 전에 route의 params에 이전 페이지 path를 넣어서 전달하여 이전 페이지를 확인할 수 있게 했구요 :)

이건 아직 구현하지 못했다는게 많이 아쉽네요.. 🥲
이런 방법이 좋은 방법인지는 잘 모르겠어서 혹시 더 좋은 의견 남겨주시면 참고하도록 하겠습니닷!

2022-02-14 17:19 UTC, daaeaad commented on mission/src/components/Footer.vue
> +        <div data-test="" class="flex row align_center lay_1">
이런게 있었네요 😂 감사합니다!!

2022-02-14 17:32 UTC, daaeaad commented on mission/src/router/index.js
> +    beforeEnter: (to, from) => {
+ 답변 남기면서 생각난건데 상품 상세 페이지랑 장바구니 페이지를 통해 결제 페이지로 넘어온게 아니라면 정상적인 접근이 아닐 가능성이 있으니까 다시 이전 페이지로 리다이렉트 시키는 로직을 추가하면 보안성을 높일 수 있을 것 같습니다 🧐

2022-02-15 02:00 UTC, ohyein00 commented on mission/src/router/index.js
> +    beforeEnter: (to, from) => {
오, 주문하기 로직에 따른 장바구니 삭제 여부는 생각하지 못하고 있었는데 함께 도움 얻고 갑니다
역시 다애님 정말 꼼꼼하시네요👍

2022-02-15 02:20 UTC, ohyein00 commented
- store의 getter 함수들이 각 역할에 맞게 잘 분리되어 있다고 생각했어요! 다애님 코드를 보니 제 코드에서 수정해야 할 것들이 보이네요. 많은 도움이 됐습니다!
- 다애님께서 제 코드가 깔끔하다고 말씀해주셨는데 되려 저는 그것이 꼼꼼하지 못하다고 느껴 걱정이었어서🤣 
반대로 다애님 코드에서 매번 디테일함을 배워가고 있습니다👍
- 5주동안 다애님 덕을 많이 본 것 같습니다. 감사합니다🥰

2022-02-15 02:56 UTC, 2taesung commented
정말 완성도 있는 결과물인 것 같습니다! 
실제 쇼핑몰처럼 여러 기능을 고려하신 게 느껴집니다. 
디자인도 진짜 서비스 같아요! 수고 많으셨고 감사했습니다~!

2022-02-15 03:04 UTC, allegoryj commented
안녕하세요 다애님! 남겨주신 영상 잘 보았습니다. 이번 미션에서 필요한 개념들을 잘 이해하시고 구현한 점이 보여 배울 점이 많았습니다. 추가적으로 구현하신 상품 수량 표시 버튼이나 상품을 삭제하는 기능은 저도 꼭 구현해보고 싶었는데 다애님 코드를 보며 배울 부분이 많았습니다. 5주간 고생많으셨습니다 :)

2022-02-15 10:15 UTC, jambottle approved these changes
다애님, 안녕하세요 👋 어느덧 이번이 마지막 과제 리뷰 시간이네요오-
여태껏 같은 과정의 일원으로 함께할 수 있어서 즐거웠고, 아래와 같이 마지막 피어 리뷰를 남깁니다!

> 강사님이 사전에 제공해주신 API를 사용하지는 않으셨지만, **Vuex Store에 여러 종류의 상품을 Mock Data로 담아 실제 있는 사이트처럼 완성도 높은 페이지를 구현하신 것이 인상적이었어요!** 내부에 어떤 로직을 구현해 작동시키느냐도 중요하지만, 그 로직을 바탕으로 보이는 화면 부분도 중요하기 때문에 이번 미션을 통해서 그런 부분들을 잘 만족시키신 것 같고, 정말 실제로 운영되는 사이트인 줄 알고 놀랐습니다!! ㄴ😲ㄱ

> 솔직히 더 많은 내용에 대해서 피드백 주고받을 수 있으면 좋았겠지만, 다애님이 구현하신 기능들이 되게 구체적이고 정확했다는 느낌이 들었던 데다가, 제가 아직 Composition API를 잘 몰라서 해당 부분에는 특히 이렇다 할 리뷰를 드리기가 쉽지가 않았습니다... 더 많은 노력 기울이지 못해 죄송해요 👉👈

그럼 그동안 고생 많으셨고, 앞으로도 지금처럼 파이팅하시길 기원하겠습니다 🙌

2022-02-15 10:15 UTC, jambottle commented on mission/src/components/Footer.vue
> +          <!-- / 버튼: 결제하기 -->
다애님, Code Presentation 영상과 비교해보니까 장바구니 페이지와 결제 페이지에서 이 컴포넌트를 동시에 사용하시려고 이렇게 버튼 두 개를 `v-if/v-else` 디렉티브를 활용해서 구현하신 것 같아요! 제가 이해한 게 맞겠죠? ㅎㅎㅎ

이 두 버튼을 찬찬히 뜯어보면 `v-if`에 바인딩된 조건을 제외하면 구조와 스타일이 거의 똑같은 것 같은데,
중복된 내용들을 제거하고 코드 간소화를 한다는 차원에서 버튼이 한 개만 있는 컴포넌트로 바꿔보면 어떨까요?? 🤔

부모 컴포넌트에서 해당 컴포넌트를 사용할 때에 필요한 경우에만 클릭 이벤트를 부여해준다면,
충분히 중복된 내용들을 제거하고 훨씬 깔끔하게 컴포넌트를 구성할 수 있을 것 같아서요-

2022-02-15 10:15 UTC, jambottle commented on mission/src/components/InputGroup/InputItem.vue
> +  },
일일이 props/data마다 타입과 기본값 지정해주시는 습관 좋은 것 같아요 👍

2022-02-15 10:15 UTC, jambottle commented on mission/src/store/index.js
> +    prevRoute: '',
제가 잘 모르고 질문드리는 거긴 한데... 이 항목은 꼭 전역 상태로 관리되어야 할까요?
`window` 객체나 Vue Router에 내장된 기능 같은 걸 활용하면, 굳이 전역 상태로 관리할 필요가 없지 않을까 싶어서요-

2022-02-15 12:28 UTC, daaeaad commented on mission/src/components/Footer.vue
> +          <!-- / 버튼: 결제하기 -->
으음..! 맞아요🤭!! 차라리 메서드를 하나 만들고 조건문으로 실행시키는 내용만 조건에 따라 바꿔주면 되었던 건데 왜 생각을 못했을까요 ㅠㅠ 
좋은 의견 정말 감사합니다!

2022-02-15 12:37 UTC, daaeaad commented on mission/src/store/index.js
> +    prevRoute: '',
음 저도 정말 많이 고민했던 내용이고 코멘트 보고 또 생각을 다시 해봤는데.. 역시 전역 상태로 관리할 필요는 없을 것 같아요!
작성 해놓고 방치해둔 느낌이 없잖아 있네요.. 🥲
재원님께서 의견 안 남겨주셨으면 store를 너무 남용하게 되었을 것 같은데 다시 한번 주의하게 되었어요! 감사합니다 :)

2022-02-15 13:00 UTC, jambottle commented on mission/src/store/index.js
> +    prevRoute: '',
아닙니다, 조심스레 드린 의견인데 경청해주셔서 제가 감사하죠 🙏

2022-02-15 18:08 UTC, glowing713 reviewed
[잘한 점]
- 상태관리를 적용해서 기능 요구사항을 잘 구현하신 것 같습니다! 프레젠테이션 영상을 보면서 정말 서비스하는 애플리케이션 같다는 느낌을 많이 받았습니다:)
- 특히 이번 주차는 다애님 구현하신 기능과 작성하신 코드의 양이 정말 상당한 것 같은 느낌이에요..! 대단합니다😲

[의견제시]
- 다애님 덕분에 5주동안 너무 많이 배워가는 것 같습니다🥲 5주차동안 정말 고생 많으셨습니다!!

2022-02-16 07:23 UTC, k12ms26 commented on mission/src/router/index.js
> +    beforeEnter: (to, from) => {
++ 이해했습니다!
뭔가 라우팅 적인 측면이 아니라 데이터 적인 면에서 분리를 시키고 싶은데,

예를 들어,
1) 구매하는 데이터 array를 생성해서 전역 선언후,

2-1) 상세 페이지에서 바로 구매하기로 넘어갈 경우
 - 장바구니 데이터는 아예 건드리지 않고 구매 데이터에 넣거나,

2-2) 장바구니에서 구매 데이터에 넣는 경우
 - 현재 장바구니에서 넘어온 데이터인지에 대한 flag 용도의 매개변수를 같이 함수에 넘겨줘서 구매완료까지 되면 장바구니를 비우는 시스템으로 가면 뭔가 라우터에 대한 직접적인 접근을 하지 않고 로직을 수행할 수 있을 거같기도 합니다

아예 고려치도 않은 부분인데 다애님 코드 보고 또 한번 좋은 고민을 하게 되네요 😄  넘넘 감사합니다 @daaeaad

2022-02-16 09:30 UTC, daaeaad commented on mission/src/router/index.js
> +    beforeEnter: (to, from) => {
@k12ms26  아하 그런 방법이..! 민선님께서 말씀해주신 방법이 저도 더 좋다고 생각해요!
혼자 끙끙 댔다면 거기까지 생각을 미처 못했을것 같은데 역시...🥲👍 감사합니다 ㅠㅠ

2022-02-17 18:59 UTC, lkaybob reviewed
store에 많은 요구사항을 도입한 것이 아쉽지만, 그 이외에는 잘 구현해주셨습니다. 특히 지속적으로 Composition API를 활용하여 제출해주시는 점도 돋보였으며, 테스트 코드도 요구사항을 꼼꼼히 검증하기 위해 잘 작성해주셨습니다. 이 외에는 라인 코멘트를 참고해주세요.

5주동안 고생하셨습니다.

2022-02-17 18:59 UTC, lkaybob commented on mission/src/store/index.js
> +    prevRoute: '',
애플리케이션을 실행하는 동안 history는 vue-router 객체에 저장되기 때문에 state로 관리할 필요는 없습니다.

라우팅을 할 때 이전 페이지에 대한 정보가 필요할 경우, (다른 분들이 사용하신) Navigation guard를 참고해보세요.

https://router.vuejs.org/guide/advanced/navigation-guards.html

2022-02-17 18:59 UTC, lkaybob commented on mission/src/store/index.js
> +    products: [
상품 목록 요구사항은 vuex로 구현할 필요가 있는지 생각해보셨으면 합니다.
* 상품 목록은 로컬에서 변화하는 것이 아니라 외부(API)의 변화를 받는 부분이기 때문입니다.
* 상품 목록은 4주차에서 API 호출을 하는 방식을 유지하시는 의견을 드립니다.

2022-02-17 18:59 UTC, lkaybob commented on mission/src/store/index.js
> +    setNewItem: (state, { id, num }) => {
단일 store 모듈에 store에 적용할 모든 것들을 구현하셨는데, 이럴 경우 관리하기가 어려워져 서로 관련이 있는 store 요구사항들끼리 모아 module로 나누시는 것을 권장드립니다.

https://vuex.vuejs.org/guide/modules.html

2022-02-17 18:59 UTC, lkaybob commented on mission/tests/unit/Order/Order.spec.js
> +    const store = createStore({ ...realStore, state, getters });
실제 store를 만들어서 테스트에 활용하는 경우, 일단 골격은 애플리케이션 코드 상의 store 모듈을 가져와 store 객체를 생성하고, 테스트 데이터를 주입하는 것은 action을 통했으면 더 좋았을 것 같습니다.
* 테스트 코드에서 static하게 선언한 state는 실제 애플리케이션의 구현체를 테스트하는 것이 아니기 때문입니다

2022-02-18 06:42 UTC, daaeaad commented on mission/src/store/index.js
> +    products: [
강사님 한가지 질문이 있습니다!
지금 vuex를 너무 남용한 것 같아서 전반적으로 수정을 하고 있는데요,

결제 페이지에 들어갈 주문 상품 데이터도(state의 orders)도 역시 store의 state가 아니라 결제 페이지 컴포넌트에 있는 것이 좋을까요?
(다시 생각해보니 주문 상품 목록은 결제 페이지에서만 사용하니 vuex로 구현할 필요가 없다고 느껴졌습니다.)

수정을 하게 된다면, 장바구니 페이지나 상품 상세 페이지에서 구매하기 버튼을 누르고 결제 페이지로 넘어갈때
route의 params에 주문하는 상품 정보를 넣어서 전달하는 방법이 좋지 않을까 생각하고 있습니다.

2022-02-21 03:57 UTC, merged